StartupEvents.registry("block", (event) => {
	event.create("ue_addons:the_accelerator_of_mechanism_power", "basic")
	event.create('ue_addons:quartz_ore')
		.soundType(SoundType.STONE)
		.hardness(3)
		.resistance(3)
		.tag("forge:ores")
		.tag('forge:ores/quartz')
		.tag("forge:ore_rates/dense")
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock('forge:need_iron_tool')
		.requiresTool(true)

	event.create('ue_addons:deepslate_quartz_ore')
		.soundType(SoundType.DEEPSLATE)
		.hardness(4)
		.resistance(4)
		.tag("forge:ores")
		.tag('forge:ores/quartz')
		.tag("forge:ore_rates/dense")
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock('forge:need_iron_tool')
		.requiresTool(true)
})