StartupEvents.registry("item", (event) => {
	function addItem(name) {
		return event.create(`${global.namespace}:${name}`)
	}

	addItem("fecl2")
		.texture(`${global.namespace}:item/material/salt/fecl2`)
		.tag("forge:chem_salts/iron")
		.tag("forge:chem_salts")
	addItem("feso4")
		.texture(`${global.namespace}:item/material/salt/feso4`)
		.tag("forge:chem_salts/iron")
		.tag("forge:chem_salts")

	addItem("cucl2")
		.texture(`${global.namespace}:item/material/salt/cucl2`)
		.tag("forge:chem_salts/copper")
		.tag("forge:chem_salts")
	addItem("cuso4")
		.texture(`${global.namespace}:item/material/salt/cuso4`)
		.tag("forge:chem_salts/copper")
		.tag("forge:chem_salts")

	addItem("zncl2")
		.texture(`${global.namespace}:item/material/salt/zncl2`)
		.tag("forge:chem_salts/zinc")
		.tag("forge:chem_salts")
	addItem("znso4")
		.texture(`${global.namespace}:item/material/salt/znso4`)
		.tag("forge:chem_salts/zinc")
		.tag("forge:chem_salts")

	addItem("alcl3")
		.texture(`${global.namespace}:item/material/salt/alcl3`)
		.tag("forge:chem_salts/aluminium")
		.tag("forge:chem_salts")
	addItem("al2so43")
		.texture(`${global.namespace}:item/material/salt/al2so43`)
		.tag("forge:chem_salts/aluminium")
		.tag("forge:chem_salts")

	addItem("aucl3")
		.texture(`${global.namespace}:item/material/salt/aucl3`)
		.tag("forge:chem_salts/gold")
		.tag("forge:chem_salts")
	addItem("au2so43")
		.texture(`${global.namespace}:item/material/salt/au2so43`)
		.tag("forge:chem_salts/gold")
		.tag("forge:chem_salts")

	addItem("agcl")
		.texture(`${global.namespace}:item/material/salt/agcl`)
		.tag("forge:chem_salts/silver")
		.tag("forge:chem_salts")
	addItem("ag2so4")
		.texture(`${global.namespace}:item/material/salt/ag2so4`)
		.tag("forge:chem_salts/silver")
		.tag("forge:chem_salts")

	addItem("pbcl2")
		.texture(`${global.namespace}:item/material/salt/pbcl2`)
		.tag("forge:chem_salts/lead")
		.tag("forge:chem_salts")
	addItem("pbso4")
		.texture(`${global.namespace}:item/material/salt/pbso4`)
		.tag("forge:chem_salts/lead")
		.tag("forge:chem_salts")

	addItem("crcl3")
		.texture(`${global.namespace}:item/material/salt/crcl3`)
		.tag("forge:chem_salts/chorme")
		.tag("forge:chem_salts")
	addItem("cr2so43")
		.texture(`${global.namespace}:item/material/salt/cr2so43`)
		.tag("forge:chem_salts/chorme")
		.tag("forge:chem_salts")

	addItem("sncl2")
		.texture(`${global.namespace}:item/material/salt/sncl2`)
		.tag("forge:chem_salts/tin")
		.tag("forge:chem_salts")
	addItem("snso4")
		.texture(`${global.namespace}:item/material/salt/snso4`)
		.tag("forge:chem_salts/tin")
		.tag("forge:chem_salts")

	addItem("vocl2")
		.texture(`${global.namespace}:item/material/salt/vocl2`)
		.tag("forge:chem_salts/vanadium")
		.tag("forge:chem_salts")
	addItem("voso4")
		.texture(`${global.namespace}:item/material/salt/voso4`)
		.tag("forge:chem_salts/vanadium")
		.tag("forge:chem_salts")

	addItem("uo2cl2")
		.texture(`${global.namespace}:item/material/salt/vocl2`)
		.tag("forge:chem_salts/uranium")
		.tag("forge:chem_salts")
	addItem("uo2so4")
		.texture(`${global.namespace}:item/material/salt/uo2so4`)
		.tag("forge:chem_salts/uranium")
		.tag("forge:chem_salts")

	addItem("nicl2")
		.texture(`${global.namespace}:item/material/salt/nicl2`)
		.tag("forge:chem_salts/nickel")
		.tag("forge:chem_salts")
	addItem("niso4")
		.texture(`${global.namespace}:item/material/salt/niso4`)
		.tag("forge:chem_salts/nickel")
		.tag("forge:chem_salts")

	addItem("cocl2")
		.texture(`${global.namespace}:item/material/salt/vocl2`)
		.tag("forge:chem_salts/cobalt")
		.tag("forge:chem_salts")
	addItem("coso4")
		.texture(`${global.namespace}:item/material/salt/coso4`)
		.tag("forge:chem_salts/cobalt")
		.tag("forge:chem_salts")

	addItem("oscl3")
		.texture(`${global.namespace}:item/material/salt/oscl3`)
		.tag("forge:chem_salts/osmium")
		.tag("forge:chem_salts")
	addItem("os2so43")
		.texture(`${global.namespace}:item/material/salt/os2so43`)
		.tag("forge:chem_salts/osmium")
		.tag("forge:chem_salts")

	addItem("ptcl4")
		.texture(`${global.namespace}:item/material/salt/ptcl4`)
		.tag("forge:chem_salts/platinum")
		.tag("forge:chem_salts")
	addItem("ptso42")
		.texture(`${global.namespace}:item/material/salt/ptso42`)
		.tag("forge:chem_salts/platinum")
		.tag("forge:chem_salts")

	addItem("na2so4")
		.texture(`${global.namespace}:item/material/salt/na2so4`)
		.tag("forge:chem_salts/sodium")
		.tag("forge:chem_salts")
	addItem("nacl")
		.texture(`${global.namespace}:item/material/salt/nacl`)
		.tag("forge:chem_salts/sodium")
		.tag("forge:chem_salts")

	addItem("caso4")
		.texture(`${global.namespace}:item/material/salt/caso4`)
		.tag("forge:chem_salts/calcium")
		.tag("forge:chem_salts")
	addItem("cacl2")
		.texture(`${global.namespace}:item/material/salt/cacl2`)
		.tag("forge:chem_salts/calcium")
		.tag("forge:chem_salts")

	addItem("k2so4")
		.texture(`${global.namespace}:item/material/salt/k2so4`)
		.tag("forge:chem_salts/potassium")
		.tag("forge:chem_salts")
	addItem("kcl")
		.texture(`${global.namespace}:item/material/salt/kcl`)
		.tag("forge:chem_salts/potassium")
		.tag("forge:chem_salts")
})