//水几构件
ServerEvents.recipes((event) => {
    let { create } = event.recipes
    create.compacting(
        'cmi:basic_random_mechanism',
        [
            'cmi:wooden_mechanism',
            'cmi:stone_mechanism',
            'cmi:iron_mechanism',
            'cmi:gold_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
    create.compacting(
        'cmi:mechanical_random_mechanism',
        [
            'cmi:andesite_mechanism',
            'create:precision_mechanism',
            'cmi:railway_mechanism',
            'cmi:copper_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
    create.compacting(
        'cmi:engineering_random_mechanism',
        [
            'cmi:light_engineering_mechanism',
            'cmi:heavy_engineering_mechanism',
            'cmi:coil_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
    create.compacting(
        'cmi:flux_random_mechanism',
        [
            'cmi:thermal_mechanism',
            'cmi:feinforced_mechanism',
            'cmi:resonant_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
    create.compacting(
        'cmi:magical_random_mechanism',
        [
            'cmi:nether_mechanism',
            'cmi:ender_mechanism',
            'cmi:enchanted_mechanism',
            'cmi:sculk_mechanism',
            'cmi:potion_mechanism',
            'cmi:colorful_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
    create.compacting(
        'cmi:quantum_random_mechanism',
        [
            'cmi:antimatter_mechanism',
            'cmi:structure_mechanism',
            'cmi:smart_mechanism',
            'cmi:nuclear_mechanism',
            'cmi:plasma_ingot'

        ]).superheated()
    create.compacting(
        'cmi:mekanism_random_mechanism',
        [
            'cmi:basic_mekanism_mechanism',
            'cmi:advanced_mekanism_mechanism',
            'cmi:elite_mekanism_mechanism',
            'cmi:ultimate_mekanism_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
    create.compacting(
        'cmi:final_random_mechanism',
        [
            'cmi:creative_mechanism',
            'cmi:plasma_ingot'
        ]).superheated()
})