new Schema("createdieselgenerators:basin_fermenting")
	.simpleKey("results", "outputFluidArray")
	.simpleKey("ingredients", "inputItemArray")
	.simpleKey("heatRequirement", "nonEmptyString", "heated" || "superheated")
	.simpleKey("processingTime", "intNumber", 100)

new Schema("createdieselgenerators:distillation")
	.simpleKey("results", "outputFluidArray")
	.simpleKey("ingredients", "inputFluidArray")
	.simpleKey("heatRequirement", "nonEmptyString", "heated" || "superheated")
	.simpleKey("processingTime", "intNumber", 100)