new Schema("farmersdelight:cooking")
	.simpleKey("result", "outputItem")
	.simpleKey("ingredients", "inputItemArray")
	.simpleKey("container", "inputItem", null)
	.simpleKey("cookingtime", "intNumber", 200)
	.simpleKey("experience", "floatNumber", 1.0)
	.simpleKey("recipe_book_tab", "nonBlankString", null)

new Schema("farmersdelight:cutting")
	.simpleKey("result", "outputItemArray")
	.simpleKey("ingredients", "inputItemArray")
	.dynamicKey((c, cb) => c.get("inputItem")()
		.or(new cb(2)
			.add(c.get("nonBlankString")().key("type"))
			.add(c.get("nonBlankString")().key("action"))
			.inputRole()
		).key("tool"))