StartupEvents.registry("item", e => {
    e.create("ue_addons:nature_mechanism", "basic")
    e.create("ue_addons:wooden_mechanism", "basic")
    e.create("ue_addons:stone_mechanism", "basic")
    e.create("ue_addons:iron_mechanism", "basic")
    e.create("ue_addons:copper_mechanism", "basic")
    e.create("ue_addons:andesite_mechanism", "basic")
    e.create("ue_addons:photosensitive_mechanism", "basic")
    e.create("ue_addons:gold_mechanism", "basic")
    e.create("ue_addons:thermal_mechanism", "basic")
    e.create("ue_addons:feinforced_mechanism", "basic")
    e.create("ue_addons:resonant_mechanism", "basic")
    e.create("ue_addons:railway_mechanism", "basic")
    e.create("ue_addons:ender_mechanism", "basic")
    e.create("ue_addons:light_engineering_mechanism", "basic")
    e.create("ue_addons:heavy_engineering_mechanism", "basic")
    e.create("ue_addons:enchanted_mechanism", "basic")
    e.create("ue_addons:smart_mechanism", "basic")
    e.create("ue_addons:basic_mekanism_mechanism", "basic")
    e.create("ue_addons:advanced_mekanism_mechanism", "basic")
    e.create("ue_addons:elite_mekanism_mechanism", "basic")
    e.create("ue_addons:ultimate_mekanism_mechanism", "basic")
    e.create("ue_addons:structure_mechanism", "basic")
    e.create("ue_addons:nuclear_mechanism", "basic")
    e.create("ue_addons:antimatter_mechanism", "basic")
    e.create("ue_addons:coil_mechanism", "basic")
    e.create("ue_addons:sculk_mechanism", "basic")
    e.create("ue_addons:colorful_mechanism", "basic")
        .tag('forge:dyes/black').tag('forge:dyes/blue').tag('forge:dyes/brown').tag('forge:dyes/cyan')
        .tag('forge:dyes/gray').tag('forge:dyes/green').tag('forge:dyes/light_blue').tag('forge:dyes/light_gray')
        .tag('forge:dyes/lime').tag('forge:dyes/magenta').tag('forge:dyes/orange').tag('forge:dyes/pink')
        .tag('forge:dyes/purple').tag('forge:dyes/red').tag('forge:dyes/white').tag('forge:dyes/yellow')
    e.create("ue_addons:creative_mechanism", "basic")
})
ItemEvents.modification(event => {
    event.modify('ue_addons:colorful_mechanism', item => {
        item.craftingRemainder = Item.of('ue_addons:colorful_mechanism').item;
    });
})