StartupEvents.registry("block", (event) => {
	event.create(`${global.namespace}:the_accelerator_of_mechanism_power`)

	event.create(`${global.namespace}:quartz_ore`)
		.soundType(SoundType.STONE)
		.hardness(3)
		.resistance(3)
		.tag("forge:ores")
		.tag("forge:ores/quartz")
		.tag("forge:ore_rates/dense")
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("forge:need_iron_tool")
		.requiresTool(true)

	event.create(`${global.namespace}:deepslate_quartz_ore`)
		.soundType(SoundType.DEEPSLATE)
		.hardness(4)
		.resistance(4)
		.tag("forge:ores")
		.tag("forge:ores/quartz")
		.tag("forge:ore_rates/dense")
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("forge:need_iron_tool")
		.requiresTool(true)
})