ServerEvents.recipes((event) => {
	let { mekanism } = event.recipes

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:brine").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:brine").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:brine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:brine", 200))
		.id("mekanism:rotary/brine")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:chlorine").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:chlorine").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.id("mekanism:rotary/chlorine")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:ethene").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:ethene").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:ethene", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:ethene", 200))
		.id("mekanism:rotary/ethene")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:hydrofluoric_acid").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:hydrofluoric_acid").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.id("mekanism:rotary/hydrofluoric_acid")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:hydrogen_chloride").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:hydrogen_chloride").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.id("mekanism:rotary/hydrogen_chloride")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:hydrogen").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:hydrogen").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.id("mekanism:rotary/hydrogen")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:lithium").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:lithium").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:lithium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:lithium", 200))
		.id("mekanism:rotary/lithium")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:oxygen").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:oxygen").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.id("mekanism:rotary/oxygen")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:sodium").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:sodium").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sodium", 200))
		.id("mekanism:rotary/sodium")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:steam").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:steam").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:steam", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:steam", 200))
		.id("mekanism:rotary/steam")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:sulfur_dioxide").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:sulfur_dioxide").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.id("mekanism:rotary/sulfur_dioxide")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:sulfur_trioxide").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:sulfur_trioxide").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.id("mekanism:rotary/sulfur_trioxide")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:sulfuric_acid").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:sulfuric_acid").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.id("mekanism:rotary/sulfuric_acid")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:superheated_sodium").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:superheated_sodium").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.id("mekanism:rotary/superheated_sodium")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:uranium_hexafluoride").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:uranium_hexafluoride").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.id("mekanism:rotary/uranium_hexafluoride")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("forge:uranium_oxide").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("mekanism:uranium_oxide").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.id("mekanism:rotary/uranium_oxide")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluid("minecraft:water").setAmount(200))
		.fluidOutput(IngredientUtils.getFirstFluid("minecraft:water").setAmount(200))
		.gasInput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.id("mekanism:rotary/water")

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:fluid_nitroglycerine", 1))
		.gasOutput("1x cmi:nitroglycerine")
		.fluidOutput(Fluid.of("cmi:fluid_nitroglycerine", 1))
		.gasInput("1x cmi:nitroglycerine")
})