ServerEvents.recipes((event) => {
	let { mekanism } = event.recipes

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:brine"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:brine"))
		.gasInput(MekanismType.Gas.of("mekanism:brine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:brine", 200))
		.id("mekanism:rotary/brine")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:chlorine"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:chlorine"))
		.gasInput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.id("mekanism:rotary/chlorine")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:ethene"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:ethene"))
		.gasInput(MekanismType.Gas.of("mekanism:ethene", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:ethene", 200))
		.id("mekanism:rotary/ethene")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:hydrofluoric_acid"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:hydrofluoric_acid"))
		.gasInput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.id("mekanism:rotary/hydrofluoric_acid")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:hydrogen_chloride"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:hydrogen_chloride"))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.id("mekanism:rotary/hydrogen_chloride")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:hydrogen"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:hydrogen"))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.id("mekanism:rotary/hydrogen")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:lithium"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:lithium"))
		.gasInput(MekanismType.Gas.of("mekanism:lithium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:lithium", 200))
		.id("mekanism:rotary/lithium")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:oxygen"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:oxygen"))
		.gasInput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.id("mekanism:rotary/oxygen")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:sodium"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:sodium"))
		.gasInput(MekanismType.Gas.of("mekanism:sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sodium", 200))
		.id("mekanism:rotary/sodium")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:steam"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:steam"))
		.gasInput(MekanismType.Gas.of("mekanism:steam", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:steam", 200))
		.id("mekanism:rotary/steam")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:sulfur_dioxide"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:sulfur_dioxide"))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.id("mekanism:rotary/sulfur_dioxide")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:sulfur_trioxide"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:sulfur_trioxide"))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.id("mekanism:rotary/sulfur_trioxide")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:sulfuric_acid"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:sulfuric_acid"))
		.gasInput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.id("mekanism:rotary/sulfuric_acid")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:superheated_sodium"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:superheated_sodium"))
		.gasInput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.id("mekanism:rotary/superheated_sodium")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:uranium_hexafluoride"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:uranium_hexafluoride"))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.id("mekanism:rotary/uranium_hexafluoride")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("forge:uranium_oxide"))
		.fluidOutput(IngredientUtils.getFirstFluidId("mekanism:uranium_oxide"))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.id("mekanism:rotary/uranium_oxide")

	mekanism.rotary()
		.fluidInput(IngredientUtils.getFirstFluidId("minecraft:water"))
		.fluidOutput(IngredientUtils.getFirstFluidId("minecraft:water"))
		.gasInput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.id("mekanism:rotary/water")

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:fluid_nitroglycerine", 1))
		.gasOutput("1x cmi:nitroglycerine")
		.fluidOutput(Fluid.of("cmi:fluid_nitroglycerine", 1))
		.gasInput("1x cmi:nitroglycerine")
})