Ponder.registry((event) => {
    event.create([
        "mekanism:supercharged_coil",
        "mekanism:sps_casing",
        "mekanism:sps_port"
    ]).scene("cmi:sps", "超临界移相器", "cmi:multiblock/sps", (scene, utils) => {
        scene.scaleSceneView(0.3)
        scene.showStructure(0)
        scene.idle(25)
        scene.addKeyframe()
        scene.idle(5)
        scene.world.showSection([0, 2, 0, 8, 2, 8], Direction.DOWN)
        scene.idle(15)
        scene.overlay.showOutline("blue", {}, [1, 2, 1, 7, 2, 7], 60)
        scene.text(60, "使用超临界移相器外壳与结构玻璃搭出这样的形状", [1.5, 3.5, 1])
        scene.idle(75)
        scene.addKeyframe()
        scene.text(40, "再以棱对棱的形式把同样的这个图形搭满6个面")
        scene.idle(55)
        scene.rotateCameraY(180)
        scene.addKeyframe()
        scene.idle(30)
        scene.world.showSection([1, 3, 1, 7, 8, 1], Direction.DOWN)
        scene.idle(30)
        scene.world.showSection([1, 3, 2, 1, 8, 7], Direction.DOWN)
        scene.idle(30)
        let rem1 = scene.world.showIndependentSection([7, 3, 2, 7, 8, 7], Direction.DOWN)
        scene.idle(30)
        let rem2 = scene.world.showIndependentSection([2, 3, 7, 6, 8, 7], Direction.DOWN)
        scene.idle(30)
        let rem3 = scene.world.showIndependentSection([2, 8, 6, 6, 8, 2], Direction.DOWN)
        scene.idle(30)
        scene.addKeyframe()
        scene.text(40, "但是，我们稍微移开一下它=P")
        scene.idle(55)
        scene.world.hideIndependentSection(rem1, Direction.UP)
        scene.world.hideIndependentSection(rem2, Direction.UP)
        scene.world.hideIndependentSection(rem3, Direction.UP)
        scene.idle(30)
        scene.world.setBlocks([4, 2, 4], "mekanism:sps_port")
        scene.idle(20)
        scene.addKeyframe()
        scene.overlay.showOutline("blue", {}, [4, 2, 4, 4, 2, 4], 60)
        scene.text(60, "在这个地方放置超临界移相器端口并通上大量电", [4.5, 2.5, 4])
        scene.idle(70)
        scene.world.setBlocks([4, 3, 4], "mekanism:supercharged_coil")
        scene.world.showSection([4, 3, 4], Direction.DOWN)
        scene.world.modifyBlock([4, 3, 4], (state) => state.with("facing", "up"), false)
        scene.idle(20)
        scene.addKeyframe()
        scene.overlay.showOutline("blue", {}, [4, 3, 4, 4, 3, 4], 60)
        scene.text(60, "并在这里放上增压线圈", [4.5, 3.5, 4])
        scene.idle(70)
        scene.world.showSection([7, 3, 2, 7, 8, 7], Direction.DOWN)
        scene.world.showSection([2, 3, 7, 6, 8, 7], Direction.DOWN)
        scene.world.showSection([2, 8, 6, 6, 8, 2], Direction.DOWN)
        scene.idle(20)
        scene.world.setBlocks([7, 5, 3], "mekanism:sps_port")
        scene.world.setBlocks([7, 5, 5], "mekanism:sps_port")
        scene.idle(10)
        scene.addKeyframe()
        scene.overlay.showOutline("blue", {}, [7, 5, 3, 7, 5, 5], 60)
        scene.text(60, "把其它面上几个结构玻璃替换为超临界移相器端口",[7, 5, 5])
        scene.idle(70)
        scene.world.modifyBlock([7, 5, 5], (state) => state.with("active", "true"), false)
        scene.idle(20)
        scene.overlay.showOutline("blue", {}, [7, 5, 5, 7, 5, 5], 60)
        scene.showControls(60, [6.5, 5, 5], "right")
            .rightClick()
            .withItem("mekanism:configurator")
            .whileSneaking()
        scene.addKeyframe()
        scene.text(60, "潜行右键将端口调整为输出模式")
        scene.idle(70)
        scene.text(60, "现在向输入端口使用加压管道通入钋，制造反物质吧！=D",[7, 3.5, 5])
        scene.idle(70)
    })
});