ItemEvents.tooltip((event) => {
	addCommonTooltip("ue_addons:wooden_mechanism")
	addCommonTooltip("ue_addons:stone_mechanism")
	addCommonTooltip("ue_addons:copper_mechanism")
	addCommonTooltip("ue_addons:nature_mechanism")
	addCommonTooltip("ue_addons:ender_mechanism")
	addCommonTooltip("ue_addons:photosensitive_mechanism")
	addCommonTooltip("ue_addons:cobalt_mechanism")
	addCommonTooltip("ue_addons:nether_mechanism")
	addCommonTooltip("ue_addons:pigiron_mechanism")
	addCommonTooltip("ue_addons:enchanted_mechanism")
	addCommonTooltip("ue_addons:nuclear_mechanism")
	addCommonTooltip("ue_addons:sculk_mechanism")
	addCommonTooltip("ue_addons:charged_amethyst")

	addAccelerateTooltip("ue_addons:stone_mechanism")
	addAccelerateTooltip("ue_addons:andesite_mechanism")
	addAccelerateTooltip("ue_addons:copper_mechanism")
	addAccelerateTooltip("ue_addons:iron_mechanism")
	addAccelerateTooltip("ue_addons:gold_mechanism")
	addAccelerateTooltip("ue_addons:ender_mechanism")
	addAccelerateTooltip("vintageimprovements:redstone_module")
	addAccelerateTooltip("ue_addons:enchanted_mechanism")
	addAccelerateTooltip("ue_addons:nether_mechanism")
	addAccelerateTooltip("ue_addons:cobalt_mechanism")
	addAccelerateTooltip("ue_addons:wooden_mechanism")

	addCommonTooltip("ue_addons:fecl2")
	addCommonTooltip("ue_addons:feso4")
	addCommonTooltip("ue_addons:cucl2")
	addCommonTooltip("ue_addons:cuso4")
	addCommonTooltip("ue_addons:zncl2")
	addCommonTooltip("ue_addons:znso4")
	addCommonTooltip("ue_addons:alcl3")
	addCommonTooltip("ue_addons:al2so43")
	addCommonTooltip("ue_addons:aucl3")
	addCommonTooltip("ue_addons:au2so43")
	addCommonTooltip("ue_addons:agcl")
	addCommonTooltip("ue_addons:ag2so4")
	addCommonTooltip("ue_addons:pbcl2")
	addCommonTooltip("ue_addons:pbso4")
	addCommonTooltip("ue_addons:crcl3")
	addCommonTooltip("ue_addons:cr2so43")
	addCommonTooltip("ue_addons:sncl2")
	addCommonTooltip("ue_addons:snso4")
	addCommonTooltip("ue_addons:vocl2")
	addCommonTooltip("ue_addons:voso4")
	addCommonTooltip("ue_addons:uo2cl2")
	addCommonTooltip("ue_addons:uo2so4")
	addCommonTooltip("ue_addons:nicl2")
	addCommonTooltip("ue_addons:niso4")
	addCommonTooltip("ue_addons:cocl2")
	addCommonTooltip("ue_addons:coso4")
	addCommonTooltip("ue_addons:oscl3")
	addCommonTooltip("ue_addons:os2so43")
	addCommonTooltip("ue_addons:na2so4")
	addCommonTooltip("ue_addons:nacl")
	addCommonTooltip("ue_addons:caso4")
	addCommonTooltip("ue_addons:cacl2")
	addCommonTooltip("ue_addons:k2so4")
	addCommonTooltip("ue_addons:kcl")
	addCommonTooltip("ue_addons:ptcl4")
	addCommonTooltip("ue_addons:ptso42")

	addCommonTooltip("ue_addons:fecl2_solution_bucket")
	addCommonTooltip("ue_addons:feso4_solution_bucket")
	addCommonTooltip("ue_addons:cucl2_solution_bucket")
	addCommonTooltip("ue_addons:cuso4_solution_bucket")
	addCommonTooltip("ue_addons:zncl2_solution_bucket")
	addCommonTooltip("ue_addons:znso4_solution_bucket")
	addCommonTooltip("ue_addons:alcl3_solution_bucket")
	addCommonTooltip("ue_addons:al2so43_solution_bucket")
	addCommonTooltip("ue_addons:aucl3_solution_bucket")
	addCommonTooltip("ue_addons:au2so43_solution_bucket")
	addCommonTooltip("ue_addons:agcl_solution_bucket")
	addCommonTooltip("ue_addons:ag2so4_solution_bucket")
	addCommonTooltip("ue_addons:pbcl2_solution_bucket")
	addCommonTooltip("ue_addons:pbso4_solution_bucket")
	addCommonTooltip("ue_addons:crcl3_solution_bucket")
	addCommonTooltip("ue_addons:cr2so43_solution_bucket")
	addCommonTooltip("ue_addons:sncl2_solution_bucket")
	addCommonTooltip("ue_addons:snso4_solution_bucket")
	addCommonTooltip("ue_addons:vocl2_solution_bucket")
	addCommonTooltip("ue_addons:voso4_solution_bucket")
	addCommonTooltip("ue_addons:uo2cl2_solution_bucket")
	addCommonTooltip("ue_addons:uo2so4_solution_bucket")
	addCommonTooltip("ue_addons:nicl2_solution_bucket")
	addCommonTooltip("ue_addons:niso4_solution_bucket")
	addCommonTooltip("ue_addons:cocl2_solution_bucket")
	addCommonTooltip("ue_addons:coso4_solution_bucket")
	addCommonTooltip("ue_addons:oscl3_solution_bucket")
	addCommonTooltip("ue_addons:os2so43_solution_bucket")
	addCommonTooltip("ue_addons:na2so4_solution_bucket")
	addCommonTooltip("ue_addons:nacl_solution_bucket")
	addCommonTooltip("ue_addons:caso4_solution_bucket")
	addCommonTooltip("ue_addons:cacl2_solution_bucket")
	addCommonTooltip("ue_addons:k2so4_solution_bucket")
	addCommonTooltip("ue_addons:kcl_solution_bucket")

	function addCommonTooltip(item) {
		event.add(item, Component.translate(`tooltip.${item}`.replace(":", ".")))
	}

	function addAccelerateTooltip(item) {
		event.addAdvanced(item, (item, advanced, text) => {
			if (event.shift) {
				text.add(Component.translate(`tooltip.${item.getId()}.accelerate`.replace(":", ".")))
			} else {
				text.add(Component.translate(`tooltip.${global.namespace}.acceleratable`))
			}
		})
	}

	// 地质锤的tooltip
	event.addAdvanced("ue_addons:geological_hammer",
		(item, advanced, text) => {
			if (global.isDeveloper) {
				text.add(Component.translate(`tooltip.ue_addons.geographycal_hammer.developer1`))
				text.add(Component.translate(`tooltip.ue_addons.geographycal_hammer.developer2`))
			} else {
				text.add(Component.translate(`tooltip.ue_addons.geographycal_hammer.not_developer`))
			}
		})
})