Ponder.registry((event) => {
    event.create('#ae2:p2p_attunements/me_p2p_tunnel')
        .scene("ae2:cable", "线缆", "ue_addons:ae2/standard_floor", (scene) => {
        // 显示底盘, 同时等待 20 Tick
        scene.showBasePlate()
        scene.idle(20)
        scene.world.setBlocks([2, 1, 1], "ae2:fluix_covered_dense_cable")
        scene.world.showSection([2, 1, 1], Direction.DOWN)
        scene.world.setBlocks([2, 3, 1], "ae2:fluix_smart_dense_cable")
        scene.world.showSection([2, 3, 1], Direction.DOWN)
        scene.world.setBlocks([4, 1, 1], "ae2:fluix_glass_cable")
        scene.world.showSection([4, 1, 1], Direction.DOWN)
        scene.world.setBlocks([4, 3, 1], "ae2:fluix_covered_cable")
        scene.world.showSection([4, 3, 1], Direction.DOWN)
        scene.world.setBlocks([4, 5, 1], "ae2:fluix_smart_cable")
        scene.world.showSection([4, 5, 1], Direction.DOWN)
        scene.idle(20)
        scene.text(40, "根据线缆粗细可以分为粗线缆和细线缆", [4, 2, 2])
        scene.idle(60)
        scene.text(40, "粗线缆有me致密线缆，me致密包层线缆，有32个频道数", [2, 1, 1])
        scene.idle(60)
        scene.text(40, "细线缆有me玻璃线缆，me包层线缆，me智能线缆，只有8个频道数", [4, 2, 2])
        scene.idle(60)
    })
})