Ponder.registry((event) => {
    event.create("ue_addons:the_accelerator_of_mechanism_power")
        .scene("kubejs:the_accelerator_of_mechanism_power", "构件之力催生器的用法","ue_addons:stone", (scene) => {
            scene.configureBasePlate(0, 0, 7)
            scene.showBasePlate()
            scene.idle(10)
            scene.idle(5)
            scene.world.setBlocks([3, 0, 3], "ue_addons:the_accelerator_of_mechanism_power")
            scene.idle(10)
            scene.text(30, "这是一个构件之力催生器", [3, 1, 3])
            scene.idle(40)
            scene.text(30, "使用铁质构件右键...", [3, 1, 3])
            scene.idle(40)
            scene.showControls(30, [3, 1, 3], "up")
                .rightClick()
                .withItem("ue_addons:iron_mechanism")
            scene.idle(40)
            scene.world.setBlocks([3, 0, 4], "minecraft:iron_ore")
            scene.world.setBlocks([4, 0, 3], "minecraft:iron_ore")
            scene.world.setBlocks([3, 0, 5], "minecraft:redstone_ore")
            scene.world.setBlocks([3, 0, 2], "minecraft:iron_ore")
            scene.world.setBlocks([2, 0, 5], "minecraft:iron_ore")
            scene.world.setBlocks([1, 0, 1], "minecraft:iron_ore")
            scene.text(30, "...会把周边的石头替换为矿石！", [3, 1, 3])
            scene.idle(40)
            scene.text(30, "同样的，还支持其它非常多种构件！")
            scene.idle(40)
            scene.overlay.showOutline("red", {}, [1, 0, 1, 5, 0, 5], 45)
            scene.text(45, "需要注意的是，只有周边5x5的区域才能被转化！")
            scene.idle(50)
            scene.text(45, "并且，当周围5x5的区域没有石头的时候，将不再转化！")
            scene.idle(60)
            scene.text(25, "部分构件支持特殊的石头作为底座！")
            scene.idle(30)
        })
});