StartupEvents.registry("item", (event) => {
	event.create(`${global.namespace}:fecl2`)
		.texture(`${global.namespace}:item/material/salt/fecl2`)
		.tag("forge:chem_salts/iron")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:feso4`)
		.texture(`${global.namespace}:item/material/salt/feso4`)
		.tag("forge:chem_salts/iron")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:cucl2`)
		.texture(`${global.namespace}:item/material/salt/cucl2`)
		.tag("forge:chem_salts/copper")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:cuso4`)
		.texture(`${global.namespace}:item/material/salt/cuso4`)
		.tag("forge:chem_salts/copper")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:zncl2`)
		.texture(`${global.namespace}:item/material/salt/zncl2`)
		.tag("forge:chem_salts/zinc")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:znso4`)
		.texture(`${global.namespace}:item/material/salt/znso4`)
		.tag("forge:chem_salts/zinc")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:alcl3`)
		.texture(`${global.namespace}:item/material/salt/alcl3`)
		.tag("forge:chem_salts/aluminium")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:al2so43`)
		.texture(`${global.namespace}:item/material/salt/al2so43`)
		.tag("forge:chem_salts/aluminium")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:aucl3`)
		.texture(`${global.namespace}:item/material/salt/aucl3`)
		.tag("forge:chem_salts/gold")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:au2so43`)
		.texture(`${global.namespace}:item/material/salt/au2so43`)
		.tag("forge:chem_salts/gold")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:agcl`)
		.texture(`${global.namespace}:item/material/salt/agcl`)
		.tag("forge:chem_salts/silver")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:ag2so4`)
		.texture(`${global.namespace}:item/material/salt/ag2so4`)
		.tag("forge:chem_salts/silver")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:pbcl2`)
		.texture(`${global.namespace}:item/material/salt/aucl3`)
		.tag("forge:chem_salts/lead")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:pbso4`)
		.texture(`${global.namespace}:item/material/salt/au2so43`)
		.tag("forge:chem_saltslead")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:crcl3`)
		.texture(`${global.namespace}:item/material/salt/crcl3`)
		.tag("forge:chem_salts/chorme")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:cr2so43`)
		.texture(`${global.namespace}:item/material/salt/cr2so43`)
		.tag("forge:chem_salts/chorme")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:sncl2`)
		.texture(`${global.namespace}:item/material/salt/sncl2`)
		.tag("forge:chem_salts/tin")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:snso4`)
		.texture(`${global.namespace}:item/material/salt/snso4`)
		.tag("forge:chem_salts/tin")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:vocl2`)
		.texture(`${global.namespace}:item/material/salt/vocl2`)
		.tag("forge:chem_salts/vanadium")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:voso4`)
		.texture(`${global.namespace}:item/material/salt/voso4`)
		.tag("forge:chem_salts/vanadium")
		.tag("forge:chem_salts")

	event.create(`${global.namespace}:uo2cl2`)
		.texture(`${global.namespace}:item/material/salt/vocl2`)
		.tag("forge:chem_salts/uranium")
		.tag("forge:chem_salts")
	event.create(`${global.namespace}:uo2so4`)
		.texture(`${global.namespace}:item/material/salt/uo2so4`)
		.tag("forge:chem_salts/uranium")
		.tag("forge:chem_salts")
})