//mek的恩情还不完😭😭😭😭😭😭😭😭
Ponder.registry((event) => {
    event.create('mekanism:cardboard_box')
        .scene("cmi:cardboard_box", "集装箱", "cmi:other/cardboard_box", (scene, utils) => {
            scene.showStructure(0)
            scene.idle(25)
            scene.addKeyframe()
            scene.world.showSection([2, 1, 2], Direction.DOWN)
            scene.idle(15)
            scene.text(40, "这是一个刷怪笼", [2, 1.5, 2])
            scene.overlay.showOutline("blue", {}, [2, 1, 2, 2, 1, 2], 40)
            scene.idle(50)
            scene.addKeyframe()
            scene.text(40, "拿集装箱右键一下...")
            scene.idle(50)
            scene.showControls(10, [2, 2.5, 2], "down")
                .rightClick()
                .withItem('mekanism:cardboard_box')
            scene.idle(13)
            scene.world.setBlocks([2, 1, 2], "mekanism:cardboard_box", false)
            scene.idle(13)
            scene.text(40, "它就被集装箱包住了", [2, 1.5, 2])
            scene.overlay.showOutline("blue", {}, [2, 1, 2, 2, 1, 2], 40)
            scene.idle(50)
            scene.text(40, "此时你可以挖掉集装箱，把它带到任何地方")
            scene.idle(60)
            scene.addKeyframe()
            scene.text(40, "潜行+右键取掉集装箱", [2, 1.5, 2])
            scene.overlay.showOutline("blue", {}, [2, 1, 2, 2, 1, 2], 40)
            scene.idle(50)
            scene.showControls(10, [2, 2.5, 2], "DOWN")
                .rightClick()
                .whileSneaking()
            scene.idle(15)
            scene.world.setBlocks([2, 1, 2], 'minecraft:spawner', false)
            scene.idle(15)
        })
});