ServerEvents.recipes((event) =>{
    /*

    event.shaped('',[
        ['','',''],
        ['','',''],
        ['','','']
    ]);


    */

   //修改热力机器配方

    event.shaped('thermal:fluid_cell_frame',[
        ['minecraft:copper_ingot','ue_addons:copper_mechanism','minecraft:copper_ingot'],
        ['#forge:glass','','#forge:glass'],
        ['#forge:glass','ue_addons:thermal_mechanism','#forge:glass']
    ]);
    event.shaped('thermal:machine_frame',[
        ['ue_addons:iron_mechanism','#forge:glass','minecraft:iron_ingot'],
        ['#forge:glass','#forge:gears/tin','#forge:glass'],
        ['minecraft:iron_ingot','#forge:glass','minecraft:iron_ingot']
    ]);
    event.shaped('thermal:device_potion_diffuser',[
        ['#forge:ingots/silver','ue_addons:thermal_mechanism','#forge:ingots/silver'],
        ['#forge:glass','minecraft:glass_bottle','#forge:glass'],
        ['#forge:ingots/silver','vintageimprovements:redstone_module','#forge:ingots/silver']
    ]);
    event.shaped('thermal:device_nullifier',[
        ['#forge:ingots/silver','vintageimprovements:redstone_module','#forge:ingots/silver'],
        ['#forge:glass','minecraft:lava_bucket','#forge:glass'],
        ['#forge:ingots/silver','ue_addons:thermal_mechanism','#forge:ingots/silver']
    ]);
    event.shaped('thermal:device_xp_condenser',[
        ['#forge:ingots/silver','ue_addons:enchanted_mechanism','#forge:ingots/silver'],
        ['#forge:glass','thermal:xp_crystal','#forge:glass'],
        ['#forge:ingots/silver','ue_addons:thermal_mechanism','#forge:ingots/silver']
    ]);
    event.shaped('thermal:device_collector',[
        ['#forge:ingots/tin','','#forge:ingots/tin'],
        ['#forge:glass','minecraft:hopper','#forge:glass'],
        ['#forge:ingots/tin','ue_addons:thermal_mechanism','#forge:ingots/tin']
    ]);
    event.shaped('thermal:redstone_servo',[
        ['vintageimprovements:redstone_module','',''],
        ['','minecraft:iron_ingot',''],
        ['','','minecraft:redstone']
    ]);
    event.shaped('thermal:device_composter',[
        ['ue_addons:wooden_mechanism','ue_addons:iron_mechanism','#minecraft:planks'],
        ['#forge:glass','minecraft:composter','#forge:glass'],
        ['#minecraft:planks','vintageimprovements:redstone_module','#minecraft:planks']
    ]);
    event.shaped('thermal:device_fisher',[
        ['#minecraft:planks','ue_addons:copper_mechanism','#minecraft:planks'],
        ['#forge:glass','minecraft:fishing_rod','#forge:glass'],
        ['#minecraft:planks','ue_addons:thermal_mechanism','#minecraft:planks']
    ]);
    event.shaped('16x thermal:rf_coil',[
        ['ue_addons:gold_mechanism','',''],
        ['','minecraft:redstone',''],
        ['','','ue_addons:gold_mechanism']
    ]);
    event.shaped('thermal:dynamo_stirling',[
        ['','minecraft:redstone',''],
        ['minecraft:stone','','minecraft:stone'],
        ['ue_addons:stone_mechanism','minecraft:flint','ue_addons:stone_mechanism']
    ]);
    event.recipes.create.item_application('thermal:dynamo_compression',['thermal:dynamo_stirling','ue_addons:thermal_mechanism'])
    event.recipes.create.item_application('thermal:dynamo_disenchantment',['thermal:dynamo_compression','ue_addons:enchanted_mechanism'])
    event.recipes.create.item_application('thermal:dynamo_magmatic',['thermal:dynamo_compression','ue_addons:feinforced_mechanism'])
    event.shaped('thermal:dynamo_gourmand',[
        ['','',''],
        ['','ue_addons:pigiron_mechanism',''],
        ['minecraft:bone','thermal:dynamo_compression','minecraft:bone']
    ]);
    event.shaped('thermal:machine_crafter',[
        ['','minecraft:crafting_table',''],
        ['','thermal:machine_frame',''],
        ['#forge:ingots/tin','ue_addons:copper_mechanism','#forge:ingots/tin']
    ]);
    event.shaped('thermal:machine_bottler',[
        ['','thermal:machine_frame',''],
        ['','create:spout',''],
        ['','ue_addons:thermal_mechanism','']
    ]);
    event.recipes.create.item_application('thermal:machine_crucible',['thermal:machine_frame','ue_addons:nether_mechanism'])
    event.shaped('thermal:machine_press',[
        ['','',''],
        ['thermal:machine_frame','create:mechanical_press','createaddition:electric_motor'],
        ['','ue_addons:thermal_mechanism','']
    ]);
    event.shaped('thermal:machine_centrifuge',[
        ['','ue_addons:coil_mechanism',''],
        ['','vintageimprovements:centrifuge',''],
        ['','thermal:machine_frame','']
    ]);
    event.shaped('thermal:machine_furnace',[
        ['','vintageimprovements:redstone_module',''],
        ['','thermal:machine_frame',''],
        ['','minecraft:furnace','']
    ]);
    event.recipes.create.item_application('thermal:machine_pyrolyzer',['thermal:machine_crucible','ue_addons:feinforced_mechanism'])
    event.shaped('thermal:machine_pulverizer',[
        ['','create:chute',''],
        ['','thermal:machine_frame',''],
        ['','ue_addons:iron_mechanism','']
    ]);
    event.shaped('thermal:machine_sawmill',[
        ['','create:mechanical_saw',''],
        ['','thermal:machine_frame',''],
        ['','ue_addons:thermal_mechanism','']
    ]);
    const DeleteRecipes = [
        'thermal:fluid_cell_frame',
        'thermal:machine_frame',
        'thermal:device_potion_diffuser',
        'thermal:device_nullifier',
        'thermal:device_xp_condenser',
        'thermal:device_collector',
        'thermal:redstone_servo',
        'thermal:device_composter',
        'thermal:device_fisher',
        'thermal:rf_coil',
        'thermal:dynamo_stirling',
        'thermal:dynamo_compression',
        'thermal:dynamo_disenchantment',
        'thermal:dynamo_magmatic',
        'thermal:dynamo_gourmand',
        'thermal:machine_crafter',
        'thermal:machine_bottler',
        'thermal:machine_crucible',
        'thermal:machine_press',
        'thermal:machine_centrifuge',
        'thermal:machine_furnace',
        'thermal:machine_pyrolyzer',
        'thermal:machine_pulverizer',
        'thermal:machine_sawmill'
    ]
    for (let num = 0; num < 24; num++) {
        let WillDelete = DeleteRecipes[num]
        event.remove({output:WillDelete})
    }
})