ServerEvents.genericLootTables((event) => {
	event.addGeneric("ue_addons:gameplay/random_mechanisms/basic", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x minecraft:iron_ingot").randomChance(0.125)
			pool.addItem("4x minecraft:copper_ingot").randomChance(0.25)
			pool.addItem("4x minecraft:gold_ingot").randomChance(0.125)
			pool.addItem("8x minecraft:stone").randomChance(0.25)
			pool.addItem("8x tconstruct:seared_stone").randomChance(0.25)
			pool.addItem("8x minecraft:andesite").randomChance(0.25)
			pool.addItem("4x minecraft:clay").randomChance(0.25)
			pool.addItem("8x minecraft:sand").randomChance(0.25)
			pool.addItem("4x minecraft:flint").randomChance(0.25)
			pool.addItem("8x minecraft:deepslate").randomChance(0.25)
			pool.addItem("4x minecraft:oak_sapling").randomChance(0.125)
			pool.addItem("4x minecraft:birch_sapling").randomChance(0.125)
			pool.addItem("4x thermal:rubberwood_sapling").randomChance(0.125)
			pool.addItem("4x tconstruct:earth_slime_sapling").randomChance(0.125)
			pool.addItem("4x minecraft:oak_log").randomChance(0.25)
			pool.setUniformRolls(2, 4)
		})
	})
	event.addGeneric("ue_addons:gameplay/random_mechanisms/mechanical", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x create_andesite_alloy").randomChance(0.25)
			pool.addItem("4x create:zinc_ingot").randomChance(0.125)
			pool.addItem("4x create:brass_ingot").randomChance(0.125)
			pool.addItem("8x create:shaft").randomChance(0.125)
			pool.addItem("4x create:cogwheel").randomChance(0.125)
			pool.addItem("8x minecraft:redstone").randomChance(0.125)
			pool.addItem("4x create:polished_rose_quartz").randomChance(0.25)
			pool.addItem("4x minecraft:iron_ingot").randomChance(0.25)
			pool.addItem("8x minecraft:copper_ingot").randomChance(0.25)
			pool.addItem("4x minecraft:gold_ingot").randomChance(0.25)
			pool.setUniformRolls(3, 6)
		})
	})
	event.addGeneric("ue_addons:gameplay/random_mechanisms/engineering", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x immersiveengineering:ingot_aluminum").randomChance(0.25)
			pool.addItem("4x thermal:nickel_ingot").randomChance(0.125)
			pool.addItem("4x thermal:lead_ingot").randomChance(0.125)
			pool.addItem("4x tconstruct:steel_ingot").randomChance(0.125)
			pool.addItem("4x immersiveengineering:coal_coke").randomChance(0.25)
			pool.addItem("8x immersiveengineering:treated_wood_horizontal").randomChance(0.25)
			pool.addItem("4x immersiveengineering:component_iron").randomChance(0.25)
			pool.addItem("4x immersiveengineering:component_steel").randomChance(0.125)
			pool.addItem("8x minecraft:iron_ingot").randomChance(0.25)
			pool.addItem("8x minecraft:copper_ingot").randomChance(0.25)
			pool.addItem("4x minecraft:gold_ingot").randomChance(0.25)
			pool.addItem("8x minecraft:redstone").randomChance(0.125)
			pool.setUniformRolls(3, 6)
		})
	})
	event.addGeneric("ue_addons:gameplay/random_mechanisms/flux", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x thermal:tin_ingot").randomChance(0.25)
			pool.addItem("4x thermal:lead_ingot").randomChance(0.125)
			pool.addItem("4x thermal:silver_ingot").randomChance(0.125)
			pool.addItem("4x thermal:nickel_ingot").randomChance(0.125)
			pool.addItem("4x thermal:apatite").randomChance(0.25)
			pool.addItem("4x thermal:cinnabar").randomChance(0.25)
			pool.addItem("4x thermal:niter").randomChance(0.25)
			pool.addItem("4x thermal:sulfur").randomChance(0.25)
			pool.addItem("4x thermal:bitumen").randomChance(0.25)
			pool.addItem("8x minecraft:iron_ingot").randomChance(0.25)
			pool.addItem("8x minecraft:copper_ingot").randomChance(0.25)
			pool.addItem("4x minecraft:gold_ingot").randomChance(0.25)
			pool.addItem("8x minecraft:redstone").randomChance(0.25)
			pool.addItem("4x minecraft:diamond").randomChance(0.125)
			pool.addItem("4x minecraft:ender_pearl").randomChance(0.25)
			pool.addItem("4x thermal:redstone_servo").randomChance(0.25)
			pool.addItem("4x thermal:rf_coil").randomChance(0.125)
			pool.addItem("4x minecraft:blaze_powder").randomChance(0.01)
			pool.addItem("4x thermal:basalz_powder").randomChance(0.01)
			pool.addItem("4x thermal:blitz_powder").randomChance(0.01)
			pool.addItem("4x thermal:blizz_powder").randomChance(0.01)
			pool.setUniformRolls(2, 4)
		})
	})
	event.addGeneric("ue_addons:gameplay/random_mechanisms/magical", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x minecraft:lapis_lazuli").randomChance(0.25)
			pool.addItem("4x create:experience_nugget").randomChance(0.25)
			pool.addItem(Item.of("minecraft:potion", "{Potion:'minecraft:night_vision'}"))
				.randomChance(0.125)
			pool.addItem(Item.of("minecraft:potion", "{Potion:'minecraft:swiftness'}"))
				.randomChance(0.125)
			pool.addItem("4x minecraft:ender_pearl").randomChance(0.25)
			pool.addItem("4x minecraft:sculk").randomChance(0.25)
			pool.addItem("4x minecraft:quartz").randomChance(0.25)
			pool.addItem("4x minecraft:blaze_rod").randomChance(0.125)
			pool.addItem("4x minecraft:netherite_scrap").randomChance(0.125)
			pool.addItem("4x minecraft:gold_ingot").randomChance(0.25)
			pool.setUniformRolls(4, 8)
		})
	})
	event.addGeneric("ue_addons:gameplay/random_mechanisms/quantum", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x ae2:singularity").randomChance(0.125)
			pool.addItem("4x ae2:quantum_entangled_singularity").randomChance(0.125)
			pool.addItem("4x ae2:fluix_crystal").randomChance(0.25)
			pool.addItem("4x ae2:matter_ball").randomChance(0.25)
			pool.addItem("4x ae2:cell_component_1k").randomChance(0.25)
			pool.addItem("4x ae2:logic_processor").randomChance(0.25)
			pool.addItem("4x ae2:calculation_processor").randomChance(0.25)
			pool.addItem("4x ae2:engineering_processor").randomChance(0.25)
			pool.addItem("8x ae2:certus_quartz_crystal").randomChance(0.25)
			pool.addItem("mekanism:pellet_plutonium").randomChance(0.05)
			pool.addItem("mekanism:pellet_polonium").randomChance(0.05)
			pool.setUniformRolls(4, 8)
		})
	})
	event.addGeneric("ue_addons:gameplay/random_mechanisms/mekanism", (loot) => {
		loot.addPool((pool) => {
			pool.addItem("4x mekanism:alloy_infused").randomChance(0.25)
			pool.addItem("4x mekanism:alloy_reinforced").randomChance(0.125)
			pool.addItem("4x mekanism:alloy_atomic").randomChance(0.125)
			pool.addItem("4x mekanism:basic_control_circuit").randomChance(0.25)
			pool.addItem("4x tconstruct:steel_ingot").randomChance(0.25)
			pool.addItem("4x mekanism:ingot_osmium").randomChance(0.25)
			pool.addItem("4x thermal:tin_ingot").randomChance(0.25)
			pool.addItem("4x thermal:lead_ingot").randomChance(0.25)
			pool.addItem("4x immersiveengineering:ingot_uranium").randomChance(0.25)
			pool.addItem("8x minecraft:iron_ingot").randomChance(0.25)
			pool.addItem("4x minecraft:gold_ingot").randomChance(0.25)
			pool.addItem("mekanism:qio_drive_base").randomChance(0.25)
			pool.addItem("4x mekanism:hdpe_pellet").randomChance(0.25)
			pool.addItem("4x minecraft:obsidian").randomChance(0.25)
			pool.setUniformRolls(3, 6)
		})
	})
})